# Generated by Django 4.0.6 on 2022-07-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('NR', 'NotRunning'), ('R', 'Running'), ('ER', 'Error')], default='NR', max_length=2)),
                ('last_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
