# Generated by Django 4.0.6 on 2022-07-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_zh', models.CharField(max_length=300)),
                ('college', models.CharField(max_length=50)),
                ('academy', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('supervisors', models.CharField(max_length=50)),
                ('research_type', models.CharField(max_length=30)),
                ('fund_type', models.CharField(max_length=30)),
                ('detail', models.TextField()),
                ('detail_zh', models.TextField()),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
