# Generated by Django 4.0.6 on 2022-07-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findphd', '0002_alter_position_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='academy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='college',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='deadline',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='detail_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='fund_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='research_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='supervisors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='title_zh',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
