# Generated by Django 4.0.6 on 2022-07-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findphd', '0003_alter_position_academy_alter_position_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='academy',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='college',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='fund_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
