# Generated by Django 4.0.6 on 2022-07-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findphd', '0006_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='best',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
