# Generated by Django 4.0.6 on 2022-07-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findphd', '0007_post_best'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
