# Generated by Django 4.0.6 on 2022-07-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findphd', '0008_alter_position_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='type',
            field=models.CharField(blank=True, choices=[('Li', '理学类'), ('Go', '工程类'), ('No', '农学类'), ('Ji', '金融类'), ('Ga', '管理类'), ('Yi', '医学类'), ('YS', '艺术类')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='academy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
